<script type="text/javascript"><!--
google_ad_client = "pub-6534378039102893"; // replace this code by your own adsense client code
google_ad_width = 120;
google_ad_height = 600;
google_ad_format = "120x600_as";
google_ad_channel ="";
google_ad_type = "text_image";
google_color_border = "F7F7F7";
google_color_bg = "F7F7F7";
google_color_link = "635D45";
google_color_url = "008000";
google_color_text = "000000";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>